version: '3'
services:

  mysql:
   image: mysql:5.5
   network_mode: host
   restart: always
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: moviedb

  user:
   image: pawanjaiswal/movie:movie-user
   restart: always
   network_mode: host
   ports:
     - "1113:1113"
   expose:
     - "1113"
   depends_on:
     - mysql

  spring:
   image: pawanjaiswal/movie:movie-spring
   restart: always
   network_mode: host
   ports:
     - "1112:1112"
   expose:
     - "1112"
   depends_on:
     - mysql
  
  angular:
    image: pawanjaiswal/movie:movie-angular
    network_mode: host
    container_name: angular-docker
    ports:
      - "4200:4200"
